### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: /../web/extensions/core/uploadImage.js'

### ISSUE THREAD

**Issue by Vagex** [ZHO-ZHO-ZHO/ComfyUI-ArtGallery#20]
D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-ArtGallery\../../web/extensions/core/uploadImage.js
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-ArtGallery\__init__.py", line 56, in <module>
    modify_js_file(uploadimg_js_file_path, new_js_content)
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-ArtGallery\__init__.py", line 5, in modify_js_file
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI-ArtGallery\\../../web/extensions/core/uploadImage.js'

Cannot import D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-ArtGallery module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI-ArtGallery\\../../web/extensions/core/uploadImage.js'

where is uploadImage.js？
help？

**Comment by iamicebomb** [comment]
check this
https://github.com/iamicebomb/ComfyUI-ArtGallery-mod-for-new-comfyui/blob/main/__init__.py

**Comment by S0LTIS** [comment]
I can confirm that this fix with init does not work.
